# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10ba7bd7c41c9dad95ebfd84579166bd5d066838c1144c355c3dcef79341f917805ee754a267d7d0014f1ad3a1f2f5d4921f6e47ef89a3ad04a8c924253d0904

test:
  secret_key_base: be73cdf756f1fa5aa89db0f0e5dcc880229a8b6fc1699cb21a3dacfa401da8fdb89926caa22e74b5cd35db47057ddbbc9ffd06529d3ecc8452a3790c928b63d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
